name: Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: benfrisbie/docker-tag-build-push-action@v1
        with:
            images: docker.io/komoliddin/js-docker-k
            registry: 'docker.io'
            username: komoliddin
            password: Gx7!dYp@92#fLm$Q